name: Sync translations with Crowdin

on:
  workflow_dispatch

jobs:
  update_and_sync_translatable_strings:
   runs-on: ubuntu-18.04
   
   steps:
    - uses: actions/checkout@master
      
    - name: Checkout
      uses: actions/checkout@v2
       
    - name: Install Qt
      run: sudo apt-get update && sudo apt-get install qt5-default qttools5-dev-tools
       
    - name: Clean old translations
      run: |
        rm ./resources/translations/linbo-gui/*-*.ts
        rm ./resources/translations/linbo-gui/*.qm
       
    - name: Update translations
      run: lupdate ./linboGUI.pro
       
    - name: Sync translations with crowdin
      uses: crowdin/github-action@1.0.16
      with:
        token: ${{ secrets.CROWDIN_API_TOKEN }}
        # upload translation template
        upload_sources: true
        # download new translations
        download_translations: true
        skip_untranslated_strings: true
        export_only_approved: true
        push_translations: false

    - name: Release translations
      run: |
        mv ./resources/translations/linbo-gui/blank.ts ./resources/translations/linbo-gui/en-GB.ts
        TRANSLATIONS=$(ls ./resources/translations/linbo-gui/*-*.ts)
        while read lang; do
          echo "Releasing $lang"
          lrelease -idbased $lang
        done <<< "$TRANSLATIONS"
          
    - name: Delete .ts files
      run: |
        rm ./resources/translations/linbo-gui/*.ts
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "New Translations from crowdin (by GitHub Action)" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
