name: Update translations from Crowdin

on:
  push:
    branches: [ master ]

jobs:
  update_translatable_strings:
   runs-on: ubuntu-18.04
   
   steps:
     - name: Install QT
       run: sudo apt-get update && sudo apt-get install qt5-default qttools5-dev-tools
       
     - name: Update translations
       run: lupdate ./linboGUI.pro
       
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    needs: [update_translatable_strings]

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.0.16
      with:
        token: ${{ secrets.CROWDIN_API_TOKEN }}
        # upload translation template
        upload_sources: true
        # download new translations
        download_translations: true
        skip_untranslated_files: true
        export_only_approved: true
        push_translations: true
        commit_message: 'New Crowdin translations by Github Action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
