name: Publish Release

on:
  workflow_dispatch

jobs:
  publish_latest_release_to_lmn_archive:
    name: Publish latest release to lmn archive
    runs-on: ubuntu-18.04
    steps:
      - name: Download assets from latest release
        uses: Itsblue/download-release-assets-action@v1
        with:
          file: ".*"
          path: "."

      - name: Copy package to lmn archive
        uses: appleboy/scp-action@master
        with:
          host: archive.linuxmuster.net
          username: github-action-user
          key: ${{ secrets.REPO_SSH_KEY }}
          port: 22
          source: "./*"
          target: "/srv/repo/mini-dinstall/incoming"

      - name: Execute publish debs script
        run: |
          echo "${{ secrets.REPO_SSH_KEY }}" > key
          chmod 600 key
          ssh -o "StrictHostKeyChecking no" -i ./key github-action-user@archive.linuxmuster.net -tt /usr/local/bin/publish-debs
          rm key
