name: Sync translations with Crowdin

on:
  push:
    branches: 
      - 'master'
    paths:
      - 'sources/**'
      - '!sources/backend/**'

  schedule:
    - cron: '00 00 * * 1'

  workflow_dispatch:

jobs:
  sync_translatable_strings:
   runs-on: ubuntu-18.04
   
   steps:
      
    - name: Checkout
      uses: actions/checkout@v2
       
    - name: Update translatable strings
      run: docker run --rm -v $(pwd):/workspace ghcr.io/linuxmuster/linuxmuster-linbo-gui-build linbo-gui-lupdate

    - name: Delete all but blank.ts
      run: |
        rm ./resources/translations/linbo-gui/*-*.ts
       
    - name: Sync translations with crowdin
      uses: crowdin/github-action@1.0.16
      with:
        token: ${{ secrets.CROWDIN_API_TOKEN }}
        # upload translation template
        upload_sources: true
        # download new translations
        download_translations: true
        skip_untranslated_strings: true
        export_only_approved: true
        push_translations: false

    - name: Commit files
      run: |
        if [ -z $(git status --porcelain) ];
        then
          echo "... No changes"
          exit 0
        fi
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "New Translations from crowdin (by GitHub Action)" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
